<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>

		<?php //$this->headLink()->appendStylesheet($this->baseUrl()."/css/jquery-forthac/jquery-ui-1.8.1.custom.css"); ?>
		<?php $this->headLink()->appendStylesheet($this->baseUrl()."/css/jquery-forthac/jquery-ui-1.8.2.custom.css"); ?>
		<?php $this->headLink()->appendStylesheet($this->baseUrl()."/css/buttons.css"); ?>

		<?php $this->headScript()->prependFile($this->baseUrl().'/js/jquery-1.3.2.min.js','text/javascript'); ?>
		<?php //$this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui-1.8.custom.min.js','text/javascript'); ?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui-1.8.2.custom.min.js','text/javascript'); ?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/buttons.js','text/javascript'); ?>

		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>
		<?php echo $this->headMeta(); ?>

		<script type="text/javascript" >

			var baseUrl = '<?php echo $this->baseUrl(); ?>';

		</script>

	</head>
	<body>

		<a href="<?php echo $this->baseUrl().$this->returnlink; ?>" class="button return" ><?php echo $this->returnlib; ?></a>

		<?php echo $this->layout()->content; ?>

	</body>
</html>