<h1>An error occurred</h1>
<h2><?php echo $this->message; ?></h2>

<?php if ('production' == APPLICATION_ENV): ?>
<h3>Exception information:</h3>

<strong>Message:</strong> <?php echo $this->exception->getMessage(); ?>
<h3>Stack trace:</h3>

<pre><?php echo $this->exception->getTraceAsString(); ?>
  </pre>
<h3>Request Parameters:</h3>

<pre><?php var_dump($this->request->getParams()); ?>
  </pre>
  <?php endif ?>