<script type="text/javascript">
	$(document).ready(function(){
		
		$("#list").jqGrid({
		   	url: baseUrl + '/ajax/getlistenonvalidee/',
			datatype: "json",
			mtype: 'POST',
			height: "100%",
			width: 650,
		   	colNames:['Créée le', 'Opération', 'Entreprise','Organisme Référent', 'Entité Opcalia'],
		   	colModel:[
				{name:'fiche_date_creation',index:'fiche_date_creation', align: "center", width: 80},
		   		{name:'fiche_id',index:'fiche_id', align: "center", width: 70},
		   		{name:'entreprise',index:'entreprise', sortable:false},
		   		{name:'org_ref',index:'org_ref', sortable:false},
		   		{name:'delegation',index:'delegation', sortable:false}
		   	],
		   	rowNum:10,
		   	rowList:[10,20,30],
		   	pager: '#pager',
		   	sortname: 'fiche_date_creation',
		    viewrecords: true,
		    sortorder: "ASC",
		    onSelectRow: function(id){
				window.location.replace(baseUrl + "/operations/visu/num/" + id);
		    },
		    loadonce: false
		}).navGrid('#pager',{edit:false,add:false,del:false,search:false});
	});
	
</script>

<table id="list" class="jqgrid"></table>
<div id="pager"></div>