<a href="<?php echo $this->baseUrl(); ?>/operations/addexistcandidat/?operation_id=<?php echo $this->operation_id; ?>" class="button add">Ajouter un candidat existant</a>
<a href="<?php echo $this->baseUrl(); ?>/operations/addnewcandidat/?operation_id=<?php echo $this->operation_id; ?>" class="button add">Créer un nouveau candidat</a>

<br />

<a href="<?php echo $this->baseUrl(); ?>/operations/visu/num/<?php echo $this->operation_id; ?>#ui-tabs-5" class="button return">Retour à l'opération</a>