<script type="text/javascript">
	$(document).ready(function(){

		$("td#questionnaire:empty").css('background-color', 'lightgrey');

		//$('.capacite_name').mbFlipText(false);
	});
</script>

<style type="text/css" media="print">

@media print
{

#header
{
font-family:arial;
background-color:#D3D3D3;
font-size: 12px;
}

#data
{
font-family:arial;
font-size: 12px;
}

}


</style>


<!--<a href="#" class="button print" >Imprimer</a>-->

<?php if( $this->demarche == "cqp" ): ?>

	<a target="_blank" href="<?php echo $this->baseUrl(); ?>/impression/tableauresultatscqp/?candidat_metier_id=<?php echo $this->candidat_metier_id; ?>&passage=<?php echo $this->passage; ?>" class="button print" >Imprimer</a>
	<a href="<?php echo $this->baseUrl(); ?>/saisie/index/metier/<?php echo $this->candidat_metier_id; ?>/" class="button add" >Saisie des notes</a>
	
	<br></br>
	<table border=1 width="100%" style="border-collapse:collapse" id="header">

		<tr>
			<td rowspan="2" style="width: 200px; text-align: center;" >
				<label><?php echo $this->titre; ?></label>
			</td>
			<td>
				<label>Candidat</label>
				<?php echo $this->nom; ?>
			</td>
			<td rowspan="3" style="text-align: center;" >
				<label><?php echo $this->type; ?></label>
				<br />
				<a href="<?php echo $this->baseUrl(); ?>/tableauresultats/index/?id=<?php echo $this->candidat_metier_id; ?>&passage=
					<?php if( $this->passage == 1 ) echo 2; ?>
					<?php if( $this->passage == 2 ) echo 1; ?>
				" class="button refresh" style="height: 15px; width: 25px;"
					<?php if( $this->passage == 1 ) echo ' title="Evaluation" '; ?>
					<?php if( $this->passage == 2 ) echo ' title="Positionnement" '; ?>
				></a>
			</td>
			<td rowspan="3" style="width: 150px; text-align: center;" >
				<label><?php echo $this->title; ?></label>
			</td>
			<td rowspan="3" style="text-align: center;" >
				<img src="<?php echo $this->baseUrl(); ?>/img/PMQ_logo.jpg" alt="PMQ" style="width:65px;height:65px;" >
			</td>
		</tr>

		<tr>
			<td>
				<label>Entreprise</label>
				<?php echo $this->entreprise; ?>
			</td>
		</tr>

		<tr>
			<td>
				<label>Organisme référent</label><br />
				<?php echo $this->organisme_referent; ?>
			</td>
			<td>
				<label>Branche</label>
				<?php echo $this->branche; ?>
			</td>
		</tr>
	</table>
<br>

<?php 
$hauteur_mini = number_format((700/(count($this->capacites))),0);
 $hauteur_maxi  = ($hauteur_mini*(count($this->capacites)));
 



$nb_aquis = count($this->livretacquis);


		if( $nb_aquis >0)
		{
				 $acq = 0;$total_aquis =0;
			
			
			$total_aquis = number_format($this->livretacquis_total,'2');
			 

			$acq = 0;$total_obs =0;
			
			 foreach( $this->observations_aquis as $observation ):
			
			 if( isset( $observation['pourcent'] ) && $observation['total'] >0 ): 
			$acq++;
			 endif; 
			
			$total_obs = $observation['pourcent']+$total_obs;
			$total_obs = number_format($total_obs,'2');	
			
		
			
			endforeach; 
			
			if($total_obs !='0')
			{
			$total_obs = $total_obs/$acq;
			}else{
				$total_obs = 0;
			}
			
			
			$total_obs = number_format($total_obs,'2');
			
			
			


				 $acq = 0;$total_ques =0;
		
		$total_ques = $this->questionnaire_total_acquis;
		$total_ques = number_format($total_ques,2);
			
			
					
			
			 $l=0;$total_note=0; $acq = 0;$total_ent =0;
				
			 $m = 0;

			 foreach( $this->entretien_aquis as $note): 
							
							$total_note+=$note;
							$l++;
							
							if($note =='100'){
								$note_affiche = '?';
							}else{
								$note_affiche = $note;
							}
							
							if($note !='100')
							{		
								$total_ent = $note_affiche+$total_ent;
								
								
							}
							
							$m++;
							 endforeach;
						 

							if($m !=0 && $total_ent != 0)
							{
			$total_ent = $total_ent/$m;
			}else{
				$total_ent = 0;
			}

		}			

		
							?>	


<?php if($nb_aquis >0){?>
	<center><a  href="<?php echo $this->baseUrl(); ?>/aquistableauresultats/index/?id=<?php echo $this->candidat_metier_id; ?>&passage=<?php echo $this->passage; ?>" class="button" >Tableau acquis de base</a>
</center>
<?php }?>
<br>
	<table border="0" width="100%" style="border-spacing: 0px;border-width:1px;padding:0px;" >
		<tr>
		
<td style="width:450px;border-width:1px;padding:0px;" valign="top">
		<?php 	echo '<center><span style="font-size: 12px;font-weight: bold"><big><big>RESULTATS</big></big></span>';?>
</td>
</tr>
</table>
		<table border="0" width="100%" style="border-spacing: 0px;border-width:1px;padding:0px;" >
		<tr>
<td style="border-width:0px;padding:0px;" valign="top">
		<table style="border-spacing: 0px;">
	<tr>
			<td style="background-color:#D3D3D3;height: 50px;border-spacing: 0px;">
				
			</td>
			</tr>
			<?php foreach( $this->capacites as $capacite ): ?>
			<tr><td style="text-align: center;height: <?php echo $hauteur_mini;?>px;background-color:#D3D3D3;width:100px;" >
				<label>
					<a href="<?php echo $this->baseUrl(); ?>/fichepedago/index/?candidat_metier_id=<?php echo $this->candidat_metier_id; ?>&capacite_id=<?php echo $capacite['num']; ?>&passage=<?php echo $this->passage; ?>" title="Fiche pédagogique" ><?php echo $capacite['nom']; ?></a>
				</label>
			</td>
			</tr>
			<?php endforeach; ?>
			<?php if($nb_aquis >0){?>
			<tr><td style="text-align: center;height: 30px;background-color:#D3D3D3;width:100px;" >
				&nbsp;
			</td>
			<tr><td style="text-align: center;height: <?php echo $hauteur_mini;?>px;background-color:#D3D3D3;width:100px;" >
				<label>
					Total
				</label>
			</td>
			</tr>
			<?php }?>
		</table>
</td>
		
<td style="width:402px;border-width:0px;padding:0px;" valign="top">
		<table style="border-spacing: 0px;">
	<tr>
			<td style="background-color:#D3D3D3;height: 50px;border-spacing: 0px;" colspan="2" >
				<label><big><big>Capacités</big></big></label>
				<br><label>Livret&nbsp;:</label>
				<?php echo $this->datelivret; ?>
			</td>
			</tr>
			<?php foreach( $this->capacites as $capacite ): ?>
			<?php if($nb_aquis > 0){?>
			<tr><td style="text-align: center;height: <?php echo $hauteur_mini;?>px;width: 402px;" colspan="2" >
				<label>
					<a href="<?php echo $this->baseUrl(); ?>/fichepedago/index/?candidat_metier_id=<?php echo $this->candidat_metier_id; ?>&capacite_id=<?php echo $capacite['num']; ?>&passage=<?php echo $this->passage; ?>" title="Fiche pédagogique" >
					<?php echo $capacite['capacite']; ?></a>
				</label>
			</td>
			</tr>
			<?php }else{?>
			<tr><td style="text-align: center;height: <?php echo $hauteur_mini;?>px;width: 402px;" colspan="2" >
				<label>
					<a href="<?php echo $this->baseUrl(); ?>/fichepedago/index/?candidat_metier_id=<?php echo $this->candidat_metier_id; ?>&capacite_id=<?php echo $capacite['num']; ?>&passage=<?php echo $this->passage; ?>" title="Fiche pédagogique" >
					<?php echo $capacite['capacite']; ?></a>
				</label>
			</td>
			</tr>
			
			<?php }?>
			<?php endforeach; ?>
			<?php if($nb_aquis > 0){?>
			
			<tr><td style="background-color:#D3D3D3;"></td><td  style="text-align: center;height: 30px;background-color:#D3D3D3;" >Livret acquis de base</td></tr>	
			<tr><td style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
				<label>
					Total Acquis de base
				</label>
			</td><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
			
				<table style="width:100%; height:40px;"  >
					<tr>
						<td style="width:50%; text-align: center; border:none; border-right-style: dotted;" ><?php if(($total_aquis)<40){echo '0';}if(($total_aquis)>69){echo '1';} if(($total_aquis)<=69 && ($total_aquis)>=40  ){echo '?';}?></td>
						<td style="width:50%; text-align: center; border: none;" ><?php echo $total_aquis; ?> %</td>
					</tr>
				</table>
				
			
			</td></tr>
			<?php }?>
		</table>
</td>
	

<td style="width:100px;border-width:0px;padding:0px;" valign="top">
		<table style="border-spacing: 0px;">
	<tr>
			<td style="background-color:#D3D3D3;height: 50px;border-spacing: 0px;">
				<label>Questionnaire technique</label><br />
				<?php echo $this->datequestionnaire; ?>
			</td>
	</tr>
			<?php foreach( $this->questionnaire as $question ): 
			
							if($this->passage == 1)
	{
	?>	
			
			
	<tr>
			<td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
				<table style="width:100%; height:30px;" >
					<tr>
						<td style="width:20px; text-align: center; border:none; border-right-style: dotted;" ><?php echo $question['caractere']; ?></td>
						<td style="width:20px; text-align: center; border: none;" ><?php echo $question['pourcent']; ?> %</td>
					</tr>
				</table>
			</td>
	</tr>
	<?php }else{?>
	<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;background-color:#D3D3D3;" >
			
			</td></tr>
	<?php }
		?>	
		
			<?php endforeach; ?>	
			<?php if($nb_aquis >0){?>
				<tr><td  style="text-align: center;height: 30px;background-color:#D3D3D3;" >Questionnaire acquis de base</td></tr>	
				<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
			
				<table style="width:100%; height:40px;"  >
					<tr>
						<td style="width:50%; text-align: center; border:none; border-right-style: dotted;" ><?php if(($total_ques)<40){echo '0';}if(($total_ques)>69){echo '1';} if(($total_ques)<=69 && ($total_ques)>=40  ){echo '?';}?></td>
						<td style="width:50%; text-align: center; border: none;" ><?php echo $total_ques; ?> %</td>
					</tr>
				</table>
				
			
			</td></tr>
			<?php }?>		
</table>
</td>	
	
<td style="width:100px;border-width:0px;padding:0px;" valign="top">
		<table style="border-spacing: 0px;">
			<tr>
			<td style="background-color:#D3D3D3;height:50px;border-spacing: 0px;">
				<label>Observation/Projet pro</label><br />
				<?php echo $this->dateobservation; ?>
			</td>
			</tr>
			<?php foreach( $this->observations as $observation ): ?>
			
				
			<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
			<?php if( isset( $observation['pourcent'] ) && $observation['pourcent'] != '' ){ ?>
				<table style="width:100%; height:40px;"  >
					<tr>
						<td style="width:50%; text-align: center; border:none; border-right-style: dotted;" ><?php echo $observation['caractere']; ?></td>
						<td style="width:50%; text-align: center; border: none;" ><?php echo $observation['pourcent']; ?> %</td>
					</tr>
				</table>
				
			<?php }else{ ?>
				<table style="width:100%; height:40px;"  >
					<tr>
						<td style="width:50%; text-align: center; border:none; border-right-style: dotted;" >0</td>
						<td style="width:50%; text-align: center; border: none;" >0 %</td>
					</tr>
				</table>
				
			<?php } ?>


			</td></tr>
			
		
		
			
			
			
			<?php endforeach; ?>
			<?php if($nb_aquis >0){?>
							<tr><td  style="text-align: center;height: 30px;background-color:#D3D3D3;" >Observation acquis de base</td></tr>	
			<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
		
				<table style="width:100%; height:40px;"  >
					<tr>
					<td style="width:50%; text-align: center; border:none; border-right-style: dotted;" >
						<?php if(($total_obs)<40){echo '0';}if(($total_obs)>69){echo '1';} if(($total_obs)<=69 && ($total_obs)>=40  ){echo '?';}?>
					</td>
						<td style="width:50%; text-align: center; border: none;" ><?php echo $total_obs; ?> %</td>
					</tr>
				</table>
				
			
			</td></tr>
			<?php }?>
</table>
</td>	


<td style="width:95px;border-width:0px;padding:0px;" valign="top">
		<table style="border-spacing: 0px;">
	<tr>
			<td style="background-color:#D3D3D3;height: 50px;border-spacing: 0px;">
				<label>Entretien technique</label><br />
				<?php echo $this->dateentretien; $l=0;$total_note=0;?>
			</td>
	</tr>		
			<?php foreach( $this->entretien as $note): ?>
							<?php 
							$total_note+=$note;
							$l++;
							
							if($note =='100'){
								$note_affiche = '?';
							}else{
								$note_affiche = $note;
							}
							 ?>
	 <tr>
	 		<td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
				<?php echo $note_affiche; ?>
			</td>		
	</tr>
							<?php endforeach; ?>	
							<?php if($nb_aquis >0){
							$total_ent = $total_ent*100;
							
							
							
								?>
				<tr><td  style="text-align: center;height: 30px;background-color:#D3D3D3;" >Entretien acquis de base</td></tr>				
								
						<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
			
				<table style="width:100%; height:40px;"  >
					<tr>
						
						<td style="width:50%; text-align: center; border:none; border-right-style: dotted;" ><?php if(($total_ent)<40){echo '0';}if(($total_ent)>69){echo '1';} if(($total_ent)<=69 && ($total_ent)>=40  ){echo '?';}?></td>
						<td style="width:50%; text-align: center; border: none;" ><?php echo  number_format(($total_ent),'2'); ?>%</td>

	</tr>
				</table>
				
			
			</td></tr>	
			<?php }?>				
</table>
</td>	


</tr>

<?php 
if($nb_aquis >0){
if(($total_ent)<40){$total_ent_valid='0';}if(($total_ent)>69){$total_ent_valid = '1';} if(($total_ent)<=69 && ($total_ent)>=40  ){$total_ent_valid =  '?';}

$total_note = $total_note+$total_ent_valid;
$l++;

}



							if($total_note == $l)
							{
								$tempo = "Admissible";
							}
							if($total_note < $l)
							{
								$tempo = "Non Admissible";
							}
							if($total_note > $l || $note_affiche=='')
							{
								$tempo = "A compl&eacute;ter";
							}


		

?>

	</table>
	
	<table border="0" width="100%" style="border-spacing: 0px;border-width:1px;padding:0px;" >
		<tr>
		
<td style="width:450px;border-width:1px;padding:0px;" valign="top">
		<?php 	echo '<center><span style="font-size: 12px;font-weight: bold"><big><big>Bilan : '.$tempo.'</big></big></span>';?>
</td>
</tr>
</table>

							
	
<?php if($nb_aquis >0){?>
	
	<br>
	<center><a  href="<?php echo $this->baseUrl(); ?>/aquistableauresultats/index/?id=<?php echo $this->candidat_metier_id; ?>&passage=<?php echo $this->passage; ?>" class="button" >Tableau acquis de base</a>
</center>
<br>
<?php }?>
<br>
		<table border=1 width="100%" style="border-collapse:collapse">
		<tr>
			<td style="width: 110px; background-color:#D3D3D3;" >
				<label>Commentaires Positionnement</label>
			</td>
			<td style="text-align: justify;" ><?php echo $this->commentaire; ?></td>
		</tr>
		<tr>
			<td style="width: 110px; background-color:#D3D3D3;" >
				<label>Commentaires Evaluation</label>
			</td>
			<td style="text-align: justify;" ><?php echo $this->commentaire2; ?></td>
		</tr>
		<tr>
			<td style="background-color:#D3D3D3;">
				<label>Informations complémentaires</label>
			</td>
			<td style="background-color:#D3D3D3;">
				Référent évaluateur entreprise : <?php echo $this->evaluateur; ?><br />
				Expert métier : <?php echo $this->expert; ?><br />
				Poste occupé par le candidat : <?php echo $this->poste; ?><br />
				<?php echo $this->nb_heures; ?>
			</td>
		</tr>
	</table>
<?php endif;?>

