<script type="text/javascript">
	$(document).ready(function(){

		$("td#questionnaire:empty").css('background-color', 'lightgrey');

		//$('.capacite_name').mbFlipText(false);
	});
</script>

<style type="text/css" media="print">

@media print
{

#header
{
font-family:arial;
background-color:#D3D3D3;
font-size: 12px;
}

#data
{
font-family:arial;
font-size: 12px;
}

}


</style>


<!--<a href="#" class="button print" >Imprimer</a>-->


	<a target="_blank" href="<?php echo $this->baseUrl(); ?>/impression/tableauresultatscqpacquis/?candidat_metier_id=<?php echo $this->candidat_metier_id; ?>&passage=<?php echo $this->passage; ?>" class="button print" >Imprimer</a>
	<a href="<?php echo $this->baseUrl(); ?>/saisie/index/metier/<?php echo $this->candidat_metier_id; ?>/" class="button add" >Saisie des notes</a>
	<br></br>

	<center><a  href="<?php echo $this->baseUrl(); ?>/tableauresultats/index/?id=<?php echo $this->candidat_metier_id; ?>&passage=<?php echo $this->passage; ?>" class="button" >Retour au tableau de synth&egrave;se</a>
</center>
<br>
	<table border=1 width="100%" style="border-collapse:collapse" id="header">

		<tr>
			<td rowspan="2" style="width: 200px; text-align: center;" >
				<label><?php echo $this->titre; ?></label>
			</td>
			<td>
				<label>Candidat</label>
				<?php echo $this->nom; ?>
			</td>
			<td rowspan="3" style="text-align: center;" >
				<label><?php echo $this->type; ?></label>
				<br />
				<a href="<?php echo $this->baseUrl(); ?>/tableauresultats/index/?id=<?php echo $this->candidat_metier_id; ?>&passage=
					<?php if( $this->passage == 1 ) echo 2; ?>
					<?php if( $this->passage == 2 ) echo 1; ?>
				" class="button refresh" style="height: 15px; width: 25px;"
					<?php if( $this->passage == 1 ) echo ' title="Evaluation" '; ?>
					<?php if( $this->passage == 2 ) echo ' title="Positionnement" '; ?>
				></a>
			</td>
			<td rowspan="3" style="width: 150px; text-align: center;" >
				<label><?php echo $this->title; ?></label>
			</td>
			<td rowspan="3" style="text-align: center;" >
				<img src="<?php echo $this->baseUrl(); ?>/img/PMQ_logo.jpg" alt="PMQ" style="width:65px;height:65px;" >
			</td>
		</tr>

		<tr>
			<td>
				<label>Entreprise</label>
				<?php echo $this->entreprise; ?>
			</td>
		</tr>

		<tr>
			<td>
				<label>Organisme référent</label><br />
				<?php echo $this->organisme_referent; ?>
			</td>
			<td>
				<label>Branche</label>
				<?php echo $this->branche; ?>
			</td>
		</tr>
	</table>
<br>

<?php 
$hauteur_mini = number_format((700/(count($this->capacites))),0);
 $hauteur_maxi  = ($hauteur_mini*(count($this->capacites)));
 
 
  $m = 0;
  $total_ent = 0;
			 foreach( $this->entretien as $note): 
							
							
							if($note =='100'){
								$note_affiche = '?';
							}else{
								$note_affiche = $note;
							}
							
							if($note !='100')
							{		
								$total_ent = $note_affiche+$total_ent;
								
								
							}
							$m++;
							 endforeach;
						 

							if($m !=0 && $total_ent != 0)
							{
			$total_ent = $total_ent/$m;
			}else{
				$total_ent = 0;
			}
 

?>

	<table border="0" width="100%" style="border-spacing: 0px;border-width:1px;padding:0px;" >
		<tr>
		
<td style="width:450px;border-width:1px;padding:0px;" valign="top">
		<?php 	echo '<center><span style="font-size: 12px;font-weight: bold"><big><big>RESULTATS ACQUIS DE BASE</big></big></span>';?>
</td>
</tr>
</table>
		<table border="0" width="100%" style="border-spacing: 0px;border-width:1px;padding:0px;" >
		<tr>
<td style="border-width:0px;padding:0px;" valign="top">
		<table style="border-spacing: 0px;">
	<tr>
			<td style="background-color:#D3D3D3;height: 50px;border-spacing: 0px;">
				
			</td>
			</tr>
			<?php foreach( $this->capacites as $capacite ): ?>
			<tr><td style="text-align: center;height: <?php echo $hauteur_mini;?>px;background-color:#D3D3D3;width:100px;" >
				<label>
					<a href="<?php echo $this->baseUrl(); ?>/fichepedago/index/?candidat_metier_id=<?php echo $this->candidat_metier_id; ?>&capacite_id=<?php echo $capacite['num']; ?>&passage=<?php echo $this->passage; ?>" title="Fiche pédagogique" ><?php echo $capacite['nom']; ?></a>
				</label>
			</td>
			</tr>
			<?php endforeach; ?>
			
			<tr><td style="text-align: center;height: <?php echo $hauteur_mini;?>px;background-color:#D3D3D3;width:100px;" >
				<label>
					Total
				</label>
			</td>
			</tr>
			
			
		</table>
</td>
		
<td style="width:350px;border-width:0px;padding:0px;" valign="top">
		<table style="border-spacing: 0px;">
	<tr>
			<td style="background-color:#D3D3D3;height: 50px;border-spacing: 0px;">
				<label><big><big>Savoirs</big></big></label>
				<br><label>Livret&nbsp;:</label>
				<?php echo $this->datelivret; ?>
			</td>
			</tr>
			<?php foreach( $this->capacites as $capacite ): ?>
			<tr><td style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
				<label>
					<a href="<?php echo $this->baseUrl(); ?>/fichepedago/index/?candidat_metier_id=<?php echo $this->candidat_metier_id; ?>&capacite_id=<?php echo $capacite['num']; ?>&passage=<?php echo $this->passage; ?>" title="Fiche pédagogique" ><?php echo $capacite['capacite']; ?></a>
				</label>
			</td>
			</tr>
			<?php endforeach; ?>
			
			<tr><td style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
				<label>
					Total Acquis de base
				</label>
			</td>
			</tr>
			
		</table>
</td>
	
<td style="width:100px;border-width:0px;padding:0px;" valign="top">
		<table style="border-spacing: 0px;">
			<tr>
			<td style="background-color:#D3D3D3;height:50px;width:120px;border-spacing: 0px;">
				<label>Livret Acquis</label><br />
				<?php echo $this->dateobservation; $acq = 0;$total_aquis =0;?>
			</td>
			</tr>
			<?php 
			$k=0;
			
			foreach( $this->livretacquis as $observation ): ?>

			<?php if( isset( $observation['pourcent'] ) &&  $observation['total']>0 ){?>
				<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
				<table style="width:100%; height:40px;"  >
					<tr>
						<td style="width:50%; text-align: center; border:none; border-right-style: dotted;" ><?php echo $observation['caractere']; ?></td>
						<td style="width:50%; text-align: center; border: none;" ><?php echo $observation['pourcent']; ?> %</td>
					</tr>
				</table>
							</td></tr>
			<?php 
			
			
			
			$total_aquis = $observation['pourcent']+$total_aquis;
			if($observation['pourcent'] !=''){$acq++;}
			
			}else{
			?>
				<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;background-color:#D3D3D3;" >
			
			</td></tr>
	
			<?php 
				
			} 
			
			
			
			?>

			<?php

			
			$k++;
			endforeach; 
				

			$total_aquis = number_format($this->livretacquis_total,'2');
			?>
			
			
			<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
		
				<table style="width:100%; height:40px;"  >
					<tr>
												<td style="width:50%; text-align: center; border:none; border-right-style: dotted;" ><?php if(($total_aquis)<40){echo '0';}if(($total_aquis)>69){echo '1';} if(($total_aquis)<=69 && ($total_aquis)>=40  ){echo '?';}?></td>
						<td style="width:50%; text-align: center; border: none;" ><?php echo $total_aquis; ?> %</td>
					</tr>
				</table>
				
			
			</td></tr>
			
			
</table>
</td>	



	

<td style="width:100px;border-width:0px;padding:0px;" valign="top">
		<table style="border-spacing: 0px;">
	<tr>
			<td style="background-color:#D3D3D3;height: 50px;border-spacing: 0px;">
				<label>Questionnaire technique</label><br />
				<?php echo $this->datequestionnaire; $acq = 0;$total_ques =0;?>
			</td>
	</tr>
		<?php 
		$k=0;
		foreach( $this->questionnaire as $question ):  
			if($this->passage == 1)
	{
		if( $question['total']>0 ){
	?>	
			
			
	<tr>
			<td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
				<table style="width:100%; height:30px;" >
					<tr>
						<td style="width:20px; text-align: center; border:none; border-right-style: dotted;" ><?php echo $question['caractere']; ?></td>
						<td style="width:20px; text-align: center; border: none;" ><?php echo $question['pourcent']; ?> %</td>
					</tr>
				</table>
			</td>
	</tr>
	<?php

		$total_ques = $this->questionnaire_total_acquis;
		$total_ques = number_format($total_ques,2);
		if($question['pourcent'] !=''){$acq++;}
		}else{
	?>
	<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;background-color:#D3D3D3;" >
			
			</td></tr>
	
	<?php 
	}
	
	
	}
	else{?>
	<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;background-color:#D3D3D3;" >
			
			</td></tr>
	<?php }
		
			
			
						$k++;
			?>

						<?php 
			
			endforeach; 
		
			?>
			
		<tr>
			<td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" width:100px;>
				<table style="width:100%; height:30px;" >
					<tr>
						<td style="width:50%; text-align: center; border:none; border-right-style: dotted;" ><?php if(($total_ques)<40){echo '0';}if(($total_ques)>69){echo '1';} if(($total_ques)<=69 && ($total_ques)>=40  ){echo '?';}?></td>
						<td style="width:20px; text-align: center; border: none;" ><?php echo $total_ques; ?> %</td>
					</tr>
				</table>
			</td>
	</tr>	
					
</table>
</td>	


	
<td style="width:100px;border-width:0px;padding:0px;" valign="top">
		<table style="border-spacing: 0px;">
			<tr>
			<td style="background-color:#D3D3D3;height:50px;border-spacing: 0px;">
				<label>Observation/Projet pro</label><br />
				<?php echo $this->dateobservation; $acq = 0;$total_obs =0;?>
			</td>
			</tr>
			<?php 
			$k=0;
			foreach( $this->observations as $observation ): 
			

			?>
			
			<?php if( isset( $observation['pourcent'] ) &&  $observation['total']>0 ){

			?>
			<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
				<table style="width:100%; height:40px;"  >
					<tr>
						<td style="width:50%; text-align: center; border:none; border-right-style: dotted;" ><?php echo $observation['caractere']; ?></td>
						<td style="width:50%; text-align: center; border: none;" ><?php echo $observation['pourcent']; ?> %</td>
					</tr>
				</table>
			</td></tr>	
			<?php 

			$acq++;
			}else{
				?>
				<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;background-color:#D3D3D3;" >
			
			</td></tr>	
			<?php 
			}
			
						
			$total_obs = $observation['pourcent']+$total_obs;
			
			?>
			
			<?php 
			$k++;
			endforeach; 
			
			if($total_obs !='0')
			{
			$total_obs = $total_obs/$acq;
			}else{
				$total_obs = 0;
			}
			
			$total_obs = number_format($total_obs,'2');
			
			?>
	<tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
			
				<table style="width:100%; height:40px;"  >
					<tr>
						<td style="width:50%; text-align: center; border:none; border-right-style: dotted;" ><?php if(($total_obs)<40){echo '0';}if(($total_obs)>69){echo '1';} if(($total_obs)<=69 && ($total_obs)>=40  ){echo '?';}?></td>
						<td style="width:50%; text-align: center; border: none;" ><?php echo $total_obs; ?> %</td>
					</tr>
				</table>
				
			
			</td></tr>
			
			
</table>
</td>


	



<td style="width:95px;border-width:0px;padding:0px;" valign="top">
		<table style="border-spacing: 0px;">
	<tr>
			<td style="background-color:#D3D3D3;height: 50px;border-spacing: 0px;">
				<label>Entretien technique</label><br />
				<?php echo $this->dateentretien; $l=0;$total_note=0; $acq = 0;?>
			</td>
	</tr>		
			<?php foreach( $this->entretien as $note): ?>
							<?php 
							$total_note+=$note;
							$l++;
							
							if($note =='100'){
								$note_affiche = '?';
							}else{
								$note_affiche = $note;
							}
							
							 $l=0;$total_note=0; 
				
			
							
							
							 ?>
	 <tr>
	 		<td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
				<?php echo $note_affiche; ?>
			</td>		
	</tr>
							<?php endforeach; 
							
							$total_ent = $total_ent*100;
							
							
							?>	
		 <tr><td  style="text-align: center;height: <?php echo $hauteur_mini;?>px;" >
			
				<table style="width:100%; height:40px;"  >
					<tr>
						
						<td style="width:50%; text-align: center; border:none; border-right-style: dotted;" ><?php if(($total_ent)<40){echo '0';}if(($total_ent)>69){echo '1';} if(($total_ent)<=69 && ($total_ent)>=40  ){echo '?';}?></td>
						<td style="width:50%; text-align: center; border: none;" ><?php echo number_format(($total_ent),'2'); ?>%</td>

	</tr>
				</table>
				
			
			</td></tr>					
												
</table>
</td>	


</tr>



<?php 
							if($total_note == $l)
							{
								$tempo = "Admissible";
							}
							if($total_note < $l)
							{
								$tempo = "Non Admissible";
							}
							if($total_note > $l || $note_affiche=='')
							{
								$tempo = "A compl&eacute;ter";
							}


		

?>

	</table>
	

<br>
	<center><a  href="<?php echo $this->baseUrl(); ?>/tableauresultats/index/?id=<?php echo $this->candidat_metier_id; ?>&passage=<?php echo $this->passage; ?>" class="button" >Retour au tableau de synth&egrave;se</a>	
	

<br>
<br>



