<div style="display: block; height: auto; width: 656px;margin-left:auto;margin-right:auto;position:relative;" class="ui-dialog ui-widget ui-widget-content ui-corner-all " aria-labelledby="ui-dialog-title-ficheCand">
	<div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix" style="-moz-user-select: none;text-align:center;">

		<span class="ui-dialog-title" id="ui-dialog-title-ficheCand" style="-moz-user-select: none;"></span>

	</div>
	<div id="formation" class="ui-dialog-content ui-widget-content" style="width: auto; display: block; min-height: 121px; height: auto;">

		<table width="630px" border="0" cellspacing="0" cellpadding="0">
			<tr>
				<td style="width:210px;" valign="top">Libellé de la formation :</td>
				<td style="width:210px;" valign="top"><?php echo ucwords( $this->formation['formation_libelle'] ); ?></td>
				<td style="width:210px;" valign="top"></td>
			</tr>
			<tr>
				<td>Formacode :</td>
				<td><?php echo $this->formation['formation_formacode']; ?></td>
				<td></td>
			</tr>
			<tr>
				<td>Organismes de formations :</td>
				<td>
					<ul>
						<?php echo $this->orgs_formation; ?>
					</ul>
				</td>
				<td></td>
			</tr>
		</table>

	</div>
</div>

<br />
<a href="<?php echo $this->baseUrl(); ?>/formations/update/id/<?php echo $this->formation['formation_id']; ?>" class="button modif" >Modifier</a>
<a href="<?php echo $this->baseUrl(); ?>/formations/candidats/id/<?php echo $this->formation['formation_id']; ?>" class="button script" >Liste des candidats</a>
<a href="<?php echo $this->baseUrl(); ?>/formations/" class="button return" >Retour</a>